# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb0a30075b7fae946eb9baff3b7c89b3a593717c1b667a77c035d57e9911ba5e18c7532f7183f7f7b58b3556790d2ea151297d356908282ed5ea9fa264b314b0
  google_oauth_secret: 'Google oauth secret'
  facebook_oauth_secret: 'Facebook oauth secret'

test:
  secret_key_base: e6267d27e295d4f1aa932e39fb2651e4ee144bf99984f26951e9a3461aa2e4e4912a4d1a6bdded27f81dc9106d0546b2e4314ed9440f5cc37606c59a2af18070

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_oauth_secret: <%= ENV['GOOGLE_SECRET'] %>
  facebook_oauth_secret: <%=ENV['FACEBOOK_SECRET'] %>