default_profic_pic_male: 'http://downloadicons.net/sites/default/files/cowboy-icon-50115.png'
default_profile_pic_female: 'http://downloadicons.net/sites/default/files/cowboy-girl-icons-50116.png'
default_cover_photo: 'http://res.cloudinary.com/zeus999/image/upload/e_blur:1000/v1483437708/sea-sky-beach-holiday-11_nnbuey.jpg'
